# Change these first
owner: Henchman-Legal
repo: status # The name of this repository

sites:
  - name: Add-in (eu)
    url: https://add-in.henchman.io
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees: 
      - g-jgreen
      - wtr7
  - name: Authentication API (eu)
    url: https://api-auth.eu.henchman.io/health
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Search API (eu)
    url: https://api-search.eu.henchman.io/health
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Dashboard (eu)
    url: https://dashboard.henchman.io/
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Dashboard API (eu)
    url: https://api-dashboard.eu.henchman.io/health
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Add-in (us)
    url: https://add-in.us.henchman.io
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees: 
      - g-jgreen
      - wtr7
  - name: Authentication API (us)
    url: https://api-auth.us.henchman.io/health
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Search API (us)
    url: https://api-search.us.henchman.io/health
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Dashboard (us)
    url: https://dashboard.us.henchman.io/
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Dashboard API (us)
    url: https://api-dashboard.us.henchman.io/health
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  

status-website:
  cname: status.henchman.io
  # baseUrl: /status
  logoUrl: https://henchman.io/uploads/logos/henchman.svg
  name: ''
  introTitle: ''
  introMessage: ''
  theme: ocean

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: ''

user-agent: g-jgreen ## Maybe we need to create a dedicated Henchman user account
