# Change these first
owner: Henchman-Legal
repo: status # The name of this repository

sites:
  - name: Add-in
    url: https://add-in.henchman.io
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees: 
      - g-jgreen
      - wtr7
  - name: Search API
    url: https://api-search.henchman.io/health
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Dashboard
    url: https://dashboard.henchman.io/
    method: GET
    assignees:
      - g-jgreen
      - wtr7
  - name: Dashboard API
    url: https://api-dashboard.henchman.io/health
    icon: https://henchman.io/favicon.ico
    method: GET
    assignees:
      - g-jgreen
      - wtr7

status-website:
  # cname: status.henchman.io
  baseUrl: /status
  logoUrl: https://henchman.io/uploads/HM-SVG-High-logo-white-1.svg
  name: ''
  introTitle: ''
  introMessage: ''
  navbar:
    - title: Status
      href: /
    - title: Henchman website
      href: https://henchman.io
  theme: ocean

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: ''

user-agent: g-jgreen ## Maybe we need to create a dedicated Henchman user account
